const Types = {
  POKEMON_ALL: 'POKEMON_ALL',
  POKEMON_LOADING: 'POKEMON_LOADING',
  POKEMON_ERROR: 'POKEMON_ERROR,',

  POKEMON_MULTIPLE_LOADING: 'POKEMON_MULTIPLE_LOADING',
  POKEMON_MULTIPLE_ALL: 'POKEMON_MULTIPLE_ALL',
  POKEMON_MULTIPLE_ERROR: 'POKEMON_MULTIPLE_ERROR'
}

export default Types
